name: Generate Snake Animation

on:
  schedule: # Tự động chạy mỗi ngày vào 00:00 giờ
    - cron: "0 0 * * *"
  workflow_dispatch: # Cho phép bạn chạy thủ công

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output: "github-contribution-grid-snake.svg"
      
      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Generate snake animation"
          git push

